wip update

diff --git a/bin/narchos-pkg-add b/bin/narchos-pkg-add
--- a/bin/narchos-pkg-add
+++ b/bin/narchos-pkg-add
@@ -1,8 +1,13 @@
 #!/bin/bash
 
+if omarchy-pkg-missing "$@"; then
+  sudo pacman -S --noconfirm --needed "$@" || exit 1
+fi
+
 for pkg in "$@"; do
   if ! pacman -Q "$pkg" &>/dev/null; then
-    sudo pacman -S --noconfirm "$pkg" || exit 1
+    echo -e "\033[31mError: Package '$pkg' did not install\033[0m" >&2
+    exit 1
   fi
 done
 
